{% set name = "starlette-context" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/starlette_context-{{ version }}.tar.gz
  sha256: d361a36ba2d4acca3ab680f917b25e281533d725374752d47607a859041958cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4.0
    - starlette

test:
  imports:
    - starlette_context
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tomwojcik/starlette-context
  doc_url: https://starlette-context.readthedocs.io/en/latest/
  summary: Access context in Starlette
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
