{% set name = "starlette-context" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/starlette_context-{{ version }}.tar.gz
  sha256: f6025753f8ede041778b2f2c3823e2da9df3c2d94832575bcb59374216b7c2b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4.0
    - starlette

test:
  imports:
    - starlette_context
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tomwojcik/starlette-context
  doc_url: https://starlette-context.readthedocs.io/en/latest/
  summary: Access context in Starlette
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
